[package]
name = "wasm-bundle"
version = "0.1.0"
authors = ["Jacob Torrång"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.69"
parse-display = "0.4"
fxhash = "0.2.1"

[package.metadata.wasm-pack.profile.release]
wasm-opt = ["-Oz", "--enable-mutable-globals"]