name: Github Page

on: push

jobs:
  build-page:
    name: Build page
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true

      - name: Cache pnpm
        uses: actions/cache@v2
        with:
          path: |
            ~/.pnpm-store
            **/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Cache Cargo
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'

      - uses: pnpm/action-setup@v1.2.1
        with:
          version: 5.13.5
          run_install: true

      - uses: jetli/wasm-pack-action@v0.3.0
        with:
          version: latest

      - name: Build docs
        run: pnpm run build

      - name: Push docs
        run: |
          mv docs temp

          git config pull.rebase false
          git pull
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          git switch docs 
          rm -rf docs
          mv temp docs
          git add docs
          git commit -m "[CI] Build docs"
          git push
          
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}