name: Github Page

on: push

jobs:
  build-page:
    name: Build page
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Checkout docs
        uses: actions/checkout@v2
        with:
          ref: docs 
          path: docs

      - name: Cache pnpm
        uses: actions/cache@v2
        with:
          path: |
            ~/.pnpm-store
            **/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Cache Cargo
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - uses: actions/setup-node@v2-beta
        with:
          node-version: latest

      - uses: pnpm/action-setup@v1.2.1
        with:
          version: latest
          run_install: true

      - uses: jetli/wasm-pack-action@v0.3.0
        with:
          version: latest

      - name: Build docs
        run: pnpm run build

      - uses: EndBug/add-and-commit@v5
        with:
          branch: docs
          cwd: './docs'
          message: "[CI] Build docs"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}