name: Github Page

on: push

jobs:
  build-page:
    name: Build page
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache pnpm
        uses: actions/cache@v2
        with:
          path: |
            ~/cache
            !~/cache/exclude
            ~/.pnpm-store
          key: ${{ runner.os }}-node-${{ hashFiles('**/pnpm-lock.yaml') }}

      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'

      - uses: pnpm/action-setup@v1.2.1
        with:
          version: 5.13.5
          run_install: true

      - uses: jetli/wasm-pack-action@v0.3.0

      - name: Build docs
        run: pnpm run build

      - uses: EndBug/add-and-commit@v5
        with:
          add: 'docs'
          message: 'Build docs'
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}